config/routes.rb
# frozen_string_literal: true

class UrlHelpersRedirector
  def self.method_missing(method, *args, **kwargs) # rubocop:disable Style/MethodMissing
    new(method, args, kwargs)
  end

  def initialize(url_helper, args, kwargs)
    @url_helper = url_helper
    @args = args
    @kwargs = kwargs
  end

  def call(params, _request)
    url_helpers.public_send(@url_helper, *@args, **@kwargs.merge(locale: params[:locale]))
  end

  private

  def url_helpers
    Rails.application.routes.url_helpers
  end
end

Rails.application.routes.draw do
  def available_locales
    @available_locales ||= /#{I18n.available_locales.join('|')}/
  end

  scope '(:locale)', locale: available_locales do
    root 'home#index'
    get '/page/:page', to: 'home#index'

    devise_for :users
    get '/users', to: redirect(UrlHelpersRedirector.new_user_registration_path)

    # Questions
    get '/questions/new', to: 'questions#new', as: :new_question
    get '/questions/:id(/page/:page)', to: 'questions#show', as: :question
    post '/questions/new', to: 'questions#create', as: :questions

    # Answers
    post '/questions/:id', to: 'answers#create', as: :question_answers
    get '/answers/:id', to: 'answers#permalink', as: :answer_permalink
    post '/answers/:id/best', to: 'answers#mark_as_best', as: :answer_mark_as_best
    delete '/answers/:id/best', to: 'answers#cancel_best', as: :answer_cancel_best

    # Corrections
    get '/answers/:id/correction', to: 'corrections#new', as: :suggest_correction
    post '/answers/:id/correction', to: 'corrections#create', as: :create_correction
    get '/corrections/:id/accept', to: 'corrections#accepting', as: :accepting_correction
    post '/corrections/:id/accept', to: 'corrections#accept', as: :accept_correction
    get '/corrections/:id/diff', to: 'corrections#diff', as: :correction_diff
  end
end

app/models/question.rb
# frozen_string_literal: true
class Question < ApplicationRecord
  paginates_per 10

  default_scope { order(created_at: :desc) }

  belongs_to :author, class_name: ::User
  belongs_to :best_answer, class_name: ::Answer, optional: true
  has_many :answers

  validates :title, presence: true
  validates :title, length: { within: 10..200 }, allow_blank: true

  validates :question, presence: true
  validates :question, length: { within: 20..5000 }, allow_blank: true

  attribute :title, :squished_text
  attribute :question, :squished_text
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: %i(new create)

  def new
    @question = current_user.questions.build
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      flash[:success] = t('.success')
      redirect_to @question
    else
      render 'new'
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = question_answers(@question)
    @answer = @question.answers.build if render_answer_form?
  end

  private

  def question_params
    params.require(:question).permit(:title, :question)
  end

  def question_answers(question)
    answers_scope = question.answers.includes(:author, :current_version).page(params[:page])
    AnswersWithCorrectionsQuery.new(current_user, answers_scope).results
  end

  def render_answer_form?
    request.format.html? && user_signed_in?
  end
end

app/helpers/question_helper.rb
# frozen_string_literal: true

module QuestionHelper
  WHITELIST_PAGINATION_PARAMS = %i(controller action locale id page).freeze

  # Kaminari generates URLs using all available params. It means that if the
  # previous action was "POST" #create_answer with the answer discarded
  # due to unsuccessful validation, we end up with all attributes from the
  # answer form in the params hash taking part in the URLs generation process.
  #
  # So resulting pagination URLs look like this:
  # /en/questions/62?answer%5Banswer%5D=&authenti...[snipped]...&utf8=%E2%9C%93
  #
  # To work around this issue, we need to pass Kaminari's #paginate helper a hash with
  # all the parameters we don't want to use when generating URLs explicitly set to nil.
  #
  # The #blacklisted_params generates that hash using the whitelist of allowed params.
  def blacklisted_params
    params.keys.each_with_object({}) do |param, hash|
      param = param.to_sym
      hash[param] = nil unless WHITELIST_PAGINATION_PARAMS.include?(param)
    end
  end
end

app/views/questions/_question.slim
.question class=('has-best' unless question.best_answer.nil?)

  - if local_assigns[:brief]
    .question-stats title=(t('.has_best') unless question.best_answer.nil?)
      a.question-stats-answers href=question_answers_highlight_path(question) data-turbolinks="false"
        .answer-count #{question.answers_count}
        .small #{t('shared.answers', count: question.answers_count)}

  .question-details
    h3 = link_to question.title, question

    - unless local_assigns.key?(:brief)
      .question-body
        = question.question

    .question-info
      => imprint(question.author)
      => t('.asked')
      = relative_time_tag(question.created_at)

app/views/questions/accept_correction.js.erb
var answer = $('#answer-<%= @answer.id %>')
var correction = $('<%= j(render @correction) %>')

answer.find('.correction[data-id="<%= @correction.id %>"]').remove()
answer.find('.corrections').append(correction)

var meta = $('<%= j(render 'answers/corrections_meta', answer: @answer.reload ) %>')
var updatedAnswer = $('<div class="answer-body">').text('<%= j(@new_version.text) %>')
answer.find('.corrections-meta').replaceWith(meta)
answer.find('.answer-body').replaceWith(updatedAnswer)

var bestAnswer = $('#best-answer .answer[data-id="<%= @answer.id %>"]')
if (bestAnswer.length > 0) {
  bestAnswer.find('.corrections-meta').replaceWith(meta.clone())
  bestAnswer.find('.answer-body').replaceWith(updatedAnswer.clone())
}

correction.find('time[data-time-ago]').timeago();

app/views/questions/accepting_correction.js.erb
var answer = $('#answer-<%= @answer.id %>')
var correction = answer.find('.correction[data-id="<%= @correction.id %>"]')
var acceptCorrectionButton = correction.find('.accept-correction-btn')
acceptCorrectionButton.hide()
var acceptCorrectionForm = $('<%= j(render 'corrections/accept_form') %>')

acceptCorrectionForm.on('click', 'button[type="reset"]', function () {
  acceptCorrectionForm.replaceWith($('<div class="accept-correction-form">'))
  acceptCorrectionButton.show()
})

correction.find('.accept-correction-form').replaceWith(acceptCorrectionForm)

app/views/questions/correction_diff.js.erb
var correction = $('.correction[data-id="<%= @correction.id %>"]')
var correctionBody = correction.find('.correction-body')
correctionBody.html('<%= j(render_diff @previous_version.text, @correction_version.text) %>')

app/views/questions/create_correction.js.erb
var answer = $('#answer-<%= @answer.id %>')
var correction = $('<%= j(render @correction) %>')

answer.find('.correction-form-btn').show()
answer.find('.correction-form').replaceWith($('<div class="correction-form">'))
answer.find('.corrections').prepend(correction)

var meta = $('<%= j(render 'answers/corrections_meta', answer: @answer.reload ) %>')
answer.find('.corrections-meta').replaceWith(meta)

var bestAnswerMeta = $('#best-answer .answer[data-id="<%= @answer.id %>"] .corrections-meta')
if (bestAnswerMeta.length > 0) {
  bestAnswerMeta.replaceWith(meta.clone())
}

correction.find('time[data-time-ago]').timeago();

app/views/questions/new.slim
- page_title t('.new')

.row: .col-xs-12.col-md-6.col-md-offset-3
  h2 #{t('.new')}
  = form_for(@question) do |f|
    = error_messages_for(@question)
    .form-group
      = f.label :title, class: 'control-label'
      = f.text_field :title, autofocus: true, class: 'form-control'
    .form-group
      = f.label :question, class: 'control-label'
      = f.text_area :question, class: 'form-control', rows: 10
    .form-group
      = f.submit t('.create'), class: 'btn btn-primary'

app/views/questions/show.js.erb
$('#answers')
    .html('<%= j(render @answers) %>')
    .find('time[data-time-ago]').timeago();
$('#answers-pagination').html('<%= j(paginate @answers, remote: true) %>');

var path = '<%= request.fullpath %>';

window.history.pushState({}, window.title, path);

app/views/questions/show.slim
- page_title @question.title
.row
  .col-xs-12.col-md-8.col-md-offset-2

    = render @question

    - if user_signed_in?
      = form_for(@answer, url: question_answers_path(@question.id)) do |f|
        = error_messages_for(@answer)
        .form-group
          = f.label :answer, t('.your_answer'), class: 'control-label'
          = f.text_area :answer, class: 'form-control', rows: 10
        .form-group
          = f.submit t('.answer'), class: 'btn btn-primary'

    #best-answer.best-answer
      - if @question.best_answer.present?
        h3
          => t('.best_answer')
          => link_to t('.goto_answer'), answer_permalink_path(@question.best_answer_id),
                                        data: { turbolinks: false }, class: 'btn btn-primary btn-xs'
          - if current_user?(@question.author)
            = button_to(answer_cancel_best_path(@question.best_answer.id),
                        class: 'btn btn-danger btn-xs', title: t('answers.best_answer_button.cancel'),
                        method: :delete) do
              = t('answers.best_answer_button.cancel')

        = render @question.best_answer, best: true

    .answers
      .answers-summary
        .answer-count #{@question.answers_count} #{t('shared.answers', count: @question.answers_count)}
        #answers-pagination.answer-pages
          = paginate @answers, params: blacklisted_params, remote: true
      #answers
        = render @answers

app/views/questions/suggest_correction.js.erb
var answer = $('#answer-<%= @answer.id %>')
var correctionFormButton = answer.find('.correction-form-btn')
correctionFormButton.hide()
var correctionForm = $('<%= j(render 'corrections/form') %>')

correctionForm.on('click', 'button[type="reset"]', function () {
  correctionForm.replaceWith($('<div class="correction-form">'))
  correctionFormButton.show()
})

answer.find('.correction-form').replaceWith(correctionForm)