config/routes.rb
# frozen_string_literal: true

class UrlHelpersRedirector
  def self.method_missing(method, *args, **kwargs) # rubocop:disable Style/MethodMissing
    new(method, args, kwargs)
  end

  def initialize(url_helper, args, kwargs)
    @url_helper = url_helper
    @args = args
    @kwargs = kwargs
  end

  def call(params, _request)
    url_helpers.public_send(@url_helper, *@args, **@kwargs.merge(locale: params[:locale]))
  end

  private

  def url_helpers
    Rails.application.routes.url_helpers
  end
end

Rails.application.routes.draw do
  def available_locales
    @available_locales ||= /#{I18n.available_locales.join('|')}/
  end

  scope '(:locale)', locale: available_locales do
    root 'home#index'
    get '/page/:page', to: 'home#index'

    devise_for :users
    get '/users', to: redirect(UrlHelpersRedirector.new_user_registration_path)

    # Questions
    get '/questions/new', to: 'questions#new', as: :new_question
    get '/questions/:id(/page/:page)', to: 'questions#show', as: :question
    post '/questions/new', to: 'questions#create', as: :questions

    # Answers
    post '/questions/:id', to: 'answers#create', as: :question_answers
    get '/answers/:id', to: 'answers#permalink', as: :answer_permalink
    post '/answers/:id/best', to: 'answers#mark_as_best', as: :answer_mark_as_best
    delete '/answers/:id/best', to: 'answers#cancel_best', as: :answer_cancel_best

    # Corrections
    get '/answers/:id/correction', to: 'corrections#new', as: :suggest_correction
    post '/answers/:id/correction', to: 'corrections#create', as: :create_correction
    get '/corrections/:id/accept', to: 'corrections#accepting', as: :accepting_correction
    post '/corrections/:id/accept', to: 'corrections#accept', as: :accept_correction
    get '/corrections/:id/diff', to: 'corrections#diff', as: :correction_diff
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true
class HomeController < ApplicationController
  include HomeHelper

  before_action :authenticate_user!, if: -> { tabs.mine? }

  def index
    @questions = questions.includes(:best_answer, :author).page(params[:page])
  end

  private

  # Return the appropriate Question collection for to the selected tab.
  def questions
    @questions_tabs ||= {
      mine: -> { current_user.questions },
      unanswered: -> { Question.where(answers_count: 0) }
    }
    @questions_tabs.fetch(tabs.selected, -> { Question }).call
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true
module HomeHelper
  def tabs
    @selected_tab ||= SelectedTab.new(params[:tab])
  end

  class SelectedTab
    TABS = %i(mine latest unanswered).freeze

    TABS.each do |tab|
      define_method(tab) { tab }
      define_method("#{tab}?") { selected == public_send(tab) }
    end

    attr_reader :selected

    def initialize(tab)
      tab = tab.try(:to_sym)
      @selected = TABS.include?(tab) ? tab : latest
    end
  end
end

app/views/home/_tabs.slim
ul.nav.nav-tabs
  li class=('active' if tabs.latest?) role="presentation"
    = link_to t('.latest'), root_path
  li class=('active' if tabs.unanswered?) role="presentation"
    = link_to t('.unanswered'), root_path(tab: tabs.unanswered)
  - if user_signed_in?
    li class=('active' if tabs.mine?) role="presentation"
      = link_to t('.mine'), root_path(tab: tabs.mine)

app/views/home/index.html.slim
.row
  .col-xs-12.col-md-8.col-md-offset-2
    h1 = t('shared.app.name')
    - unless user_signed_in?
      p
        ' #{t('.have_a_question')}?
        = link_to t('.sign_up'), new_user_registration_path
        | !
    = render 'tabs'
    - if @questions.empty?
      p.spacer
        ' #{t('.no_questions_yet')}.
        - if user_signed_in?
          = link_to t('.ask_a_question'), new_question_path
          | !
        - else
          = t('.sign_in_to_ask_a_question.html',
              sign_in_link: link_to(t('.sign_in'), new_user_session_path))
          | !
    - else
      #questions.questions
        = render @questions, brief: true
      #questions-pagination.question-pagination
        = paginate @questions, remote: true

app/views/home/index.js.erb
$('#questions')
    .html('<%= j(render @questions, brief: true) %>')
    .find('time[data-time-ago]').timeago();
$('#questions-pagination').html('<%= j(paginate @questions, remote: true) %>');

var path = '<%= request.fullpath %>';

window.history.pushState({}, window.title, path)