config/routes.rb
# frozen_string_literal: true

class UrlHelpersRedirector
  def self.method_missing(method, *args, **kwargs) # rubocop:disable Style/MethodMissing
    new(method, args, kwargs)
  end

  def initialize(url_helper, args, kwargs)
    @url_helper = url_helper
    @args = args
    @kwargs = kwargs
  end

  def call(params, _request)
    url_helpers.public_send(@url_helper, *@args, **@kwargs.merge(locale: params[:locale]))
  end

  private

  def url_helpers
    Rails.application.routes.url_helpers
  end
end

Rails.application.routes.draw do
  def available_locales
    @available_locales ||= /#{I18n.available_locales.join('|')}/
  end

  scope '(:locale)', locale: available_locales do
    root 'home#index'
    get '/page/:page', to: 'home#index'

    devise_for :users
    get '/users', to: redirect(UrlHelpersRedirector.new_user_registration_path)

    # Questions
    get '/questions/new', to: 'questions#new', as: :new_question
    get '/questions/:id(/page/:page)', to: 'questions#show', as: :question
    post '/questions/new', to: 'questions#create', as: :questions

    # Answers
    post '/questions/:id', to: 'answers#create', as: :question_answers
    get '/answers/:id', to: 'answers#permalink', as: :answer_permalink
    post '/answers/:id/best', to: 'answers#mark_as_best', as: :answer_mark_as_best
    delete '/answers/:id/best', to: 'answers#cancel_best', as: :answer_cancel_best

    # Corrections
    get '/answers/:id/correction', to: 'corrections#new', as: :suggest_correction
    post '/answers/:id/correction', to: 'corrections#create', as: :create_correction
    get '/corrections/:id/accept', to: 'corrections#accepting', as: :accepting_correction
    post '/corrections/:id/accept', to: 'corrections#accept', as: :accept_correction
    get '/corrections/:id/diff', to: 'corrections#diff', as: :correction_diff
  end
end

app/models/answer.rb
# frozen_string_literal: true
class Answer < ApplicationRecord
  ANSWERS_PER_PAGE = 15

  paginates_per ANSWERS_PER_PAGE

  before_create :create_initial_version

  belongs_to :author, class_name: ::User
  belongs_to :question, counter_cache: true
  # Do I really need this if I already has belongs_to :question?
  # has_one :question, foreign_key: :best_answer_id
  has_many :corrections
  belongs_to :current_version, class_name: ::Answer::Version, optional: true

  default_scope { order(created_at: :desc) }

  validates :answer, presence: true
  validates :answer, length: 20..5000, allow_blank: true

  attribute :answer, :squished_text

  # Determine the page the answer appears on.
  def page
    position = self.class.where('created_at >= ? AND question_id = ?',
                                created_at, question_id).count
    (position.to_f / ANSWERS_PER_PAGE).ceil
  end

  # Mark the answer as the best answer to the corresponding question.
  def mark_as_best
    question.update_attribute(:best_answer, self)
  end

  # Remove the best answer mark, if set.
  def remove_best_mark
    question.update_attribute(:best_answer, nil) if
      question.best_answer == self
  end

  # Check if the answer is the best answer to the corresponding question
  def best?
    question.best_answer == self
  end

  private

  # Create the initial version of the answer.
  def create_initial_version
    return if answer.blank?

    create_current_version!(text: answer)
  end
end

app/models/answer/version.rb
# frozen_string_literal: true

class Answer
  class Version < ApplicationRecord
    belongs_to :previous_version, class_name: ::Answer::Version, optional: true
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!, only: %i(create mark_as_best cancel_best)

  def create
    @question = Question.find(params[:id])
    @answer = @question.answers.build(answer_params)

    if @answer.save
      flash[:success] = t('.success')
      redirect_to answer_path(@answer)
    else
      @answers = @question.answers.page(nil)
      render 'questions/show'
    end
  end

  def permalink
    answer = Answer.find(params[:id])
    redirect_to answer_path(answer)
  end

  def mark_as_best
    answer = Answer.find(params[:id])
    return redirect_to question_path(answer.question) unless
      current_user?(answer.question.author)

    answer.mark_as_best
    redirect_to answer_path(answer)
  end

  def cancel_best
    answer = Answer.find(params[:id])
    return redirect_to question_path(answer.question) unless
      current_user?(answer.question.author)

    answer.remove_best_mark
    redirect_to question_path(answer.question)
  end

  private

  def answer_params
    params.require(:answer).permit(:answer).merge(author_id: current_user.id)
  end

  def answer_path(answer)
    page = answer.page
    page = nil if page == 1
    question_path(answer.question, page: page, focused: answer.id, anchor: "answer-#{answer.id}")
  end
end

app/views/answers/_answer.slim
.answer [ id=("answer-#{answer.id}" unless local_assigns[:best]) data-id=answer.id
          class=('focused' if !local_assigns[:best] && params[:focused].to_i == answer.id) ]
  - unless local_assigns[:best]
    .answer-header
      .best-answer-button
        = render 'answers/best_answer_button', answer: answer
      .answer-permalink
        | [
        = link_to t('.permalink'), answer_permalink_path(answer.id), data: { turbolinks: "false" }
        | ]
  .answer-body
    = answer.current_version.text
  .answer-info
    .answer-meta
      => imprint(answer.author)
      => t('.answered')
      => relative_time_tag(answer.created_at)
    = render 'answers/corrections_meta', answer: answer

  - unless local_assigns[:best]
    .new-correction
      - if user_signed_in?
        = link_to t('.suggest_correction'), suggest_correction_path(answer.id),
          class: 'btn btn-xs btn-primary correction-form-btn', remote: true
        .correction-form

    .corrections
      = render answer.corrections

app/views/answers/_best_answer_button.slim
- if answer.best?
  - if current_user?(answer.question.author)
    = button_to(answer_cancel_best_path(answer.id), class: 'btn btn-success btn-xs',
                                                    title: t('.cancel'),
                                                    method: :delete) do
      = t('.best')
  - else
    button.btn.btn-success.btn-xs type="button" disabled=true
      = t('.best')
- else
  - if current_user?(answer.question.author)
    = button_to(answer_mark_as_best_path(answer.id), class: 'btn btn-primary btn-xs',
                                                     title: t('.mark'),
                                                     method: :post) do
      = t('.mark')

app/views/answers/_corrections_meta.slim
.corrections-meta
  - unless answer.accepted_corrections_count.zero?
    => t('.corrections', count: answer.accepted_corrections_count)
  - if current_user?(answer.author) && !answer.pending_corrections_count.zero?
    | (#{t('.pending_corrections', count: answer.pending_corrections_count)})